myproject/blog_posts/forms.py
# FORMS FOR BLOG POSTS

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class BLogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

myproject/users/forms.py
# USER REGISTRATION, LOGIN, UPDATE FORMS 

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField, FileAllowed

from flask_login import current_user
from myproject.modules import User

class LoginForm(FlaskForm):
    email = StringField("Email", validators= [DataRequired(), Email()])
    password = PasswordField("Password",validators=[DataRequired()])
    submit = SubmitField("Log In")

class RegistrationForm(FlaskForm):
    email = StringField("Email", validators= [DataRequired(), Email()])
    password = PasswordField("Password",validators=[DataRequired(),EqualTo('pass_confirm', message = 'Password does not match')])
    username = StringField("Username", validators=[DataRequired()])
    pass_confirm = PasswordField("Password",validators= [DataRequired()])
    submit = SubmitField("Register")

    def check_email(self,field):
        if User.query.filter_by(email= field.data).first():
            raise ValidationError('Your email has already been registered !')

    def check_username(self,field):
        if User.query.filter_by(username= field.data).first():
            raise ValidationError("This usernmae has already been taken !")


class UpdateUserForm(FlaskForm):
    email = StringField("Email", validators= [DataRequired(), Email()])
    username = StringField("Username", validators=[DataRequired()])
    picture = FileField("Update Profile Picture",validators= [FileAllowed(['jpg','png'])])
    submit = SubmitField("Update")

    def check_email(self,field):
        if User.query.filter_by(email= field.data).first():
            raise ValidationError('Your email has already been registered !')

    def check_username(self,field):
        if User.query.filter_by(username= field.data).first():
            raise ValidationError("This usernmae has already been taken !")

myproject/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


app = Flask(__name__)

### Database configuration ###
app.config['SECRET_KEY'] = 'mysecretkey'
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SQLALCHEMY_DATABASE_URI'] =  'sqlite:///'+os.path.join(basedir,'data.sqlite')

db = SQLAlchemy(app)
Migrate(app,db)


### Creating Login Manager ###
login_manager = LoginManager()

login_manager.init_app(app)
login_manager.login_view = 'users.login'

### Blueprint configuration###
from myproject.core.views import core
from myproject.users.views import users
from myproject.blog_posts.views import blog_posts

app.register_blueprint(core)
app.register_blueprint(users)
app.register_blueprint(blog_posts)

myproject/blog_posts/views.py
from flask import render_template, url_for, flash, request, redirect, Blueprint
from flask_login import current_user, login_required
from myproject import db
from myproject.modules import BlogPost
from myproject.blog_posts.forms import BLogPostForm

blog_posts = Blueprint('blog_posts',__name__)


#CREATE METHOD
@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form  = BLogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title = form.title.data,
                            text = form.text.data,
                            user_id = current_user.id)


        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Created')
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form =form)

#VIEW BLOG METHOD 
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title = blog_post.title,
                            date = blog_post.date,post = blog_post)


#UPDATE BLOG METHOD
@blog_posts.route('/<int:blog_post_id>/update', methods=['GET','POST'])
@login_required
def update(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form  = BLogPostForm()

    if form.validate_on_submit():

        blog_post.title = form.title.data
        blog_post.text = form.text.data


        db.session.commit()
        flash('Blog Updated')
        return redirect(url_for('blog_posts.blog_post', blog_post_id = blog_post_id))

    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html', title = 'Updating', form=form )


#DELETE BLOG METHOD
@blog_posts.route('/<int:blog_post_id>/delete',methods=['POST'])
@login_required
def delete_post(blog_post_id):

    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    db.session.delete(blog_post)
    db.session.commit()
    flash('Blog Deleted')
    return redirect(url_for('core.index'))

myproject/core/views.py
from flask import render_template, request, Blueprint,url_for
from myproject.modules import BlogPost

core = Blueprint('core', __name__)

# CREATING VIEWS FOR THE HOME PAGE  
@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('index.html',blog_posts= blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

myproject/users/views.py
from flask import render_template, url_for, redirect, request, Blueprint,flash
from flask_login import login_user, current_user, logout_user, login_required
from myproject import db
from myproject.users.forms import LoginForm, RegistrationForm, UpdateUserForm
from myproject.modules import User, BlogPost
from myproject.users.picture_handler import add_profile_pic


users = Blueprint('users',__name__)



#REGISTER USER
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registration!')
        return redirect(url_for('users.login'))

    return render_template('register.html',form=form)



#LOGIN USER
@users.route('/login',methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.check_password(form.password.data) and user is not None:

            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')

            if next ==None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)


#LOGOUT USER
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


#UPDATE ACCOUNT FORM
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

#USER BLOGS VIEW
@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page',1,type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)

myproject/templates/account.html
<!CREATING A TEMPLATE TO UPDATE EMAIL AND USERNAME OF THE USER!> 

{% extends 'base.html' %}
{% block content %}
 <div class="jumbotron">
   <h1 style="text-align:center">Welcome to the page {{current_user.username}}</h1>
 </div>

 <div class="container">

   <form method="POST" action="" enctype="multipart/form-data">

     {{form.hidden_tag()}}
     <div class="form-group">
       {{form.username.label(class = 'form-group')}}
       {{form.username(class = 'form-control')}}
     </div>
     <div class="form-group">
       {{form.email.label(class = 'form-group')}}
       {{form.email(class = 'form-control')}}
     </div>
     <div class="form-group">
       {{form.submit(class = "btn btn-primary")}}
     </div>

   </form>

 </div>
{% endblock %}

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </head>
  <body>

    
    <nav class="navbar navbar-expand-lg navbar-dark "style="background-color:#141B1A">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav mr-auto ">

        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('core.index')}}">Home</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('core.info')}}">About</a>
        </li>

        {% if current_user.is_authenticated %}

        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('blog_posts.create_post')}}">Create Post</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('users.logout')}}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('users.login')}}">Log In</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
        </li>

        {% endif %}

      </ul>
    </nav>

  <div class="container-full-bg">
    {% block content %}

    {% endblock %}
  </div>

  </body>
</html>

myproject/templates/blog_post.html
<!CREATING TEMPLATE TO UPDATE OR DELETE THE BLOGS OF USER!>

{% extends 'base.html' %}

{% block content %}

<div class="jumbotron">
  <h1 style="text-align:center">{{post.title}}</h1><br>
  <h2>Written by: {{post.author.username}}</h2>
  <h3>Published: {{post.date.strftime('%B %d %Y')}}</h3><br>
  <p>{{post.text}}</p>

  {% if post.author == current_user %}
  <div >
    <a class="btn btn-secondary" href="{{url_for('blog_posts.update',blog_post_id = post.id)}}">Update</a>
    <button type="button" class='btn btn-danger' data-toggle="modal" data-target="#del_modal">Delete</button>
  </div>

</div>

<!CREATING A POP UP BOX!> 
<div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

  {% endif %}


{% endblock content %}

myproject/templates/create_post.html
<!CREATING TEMPLATE TO WRITE A NEW POST!>

{% extends 'base.html'%}

{% block content %}

  <div class="container">
    <form class="form-group" method="POST">
      {{form.hidden_tag()}}
      <div class="form-group">
        {{form.title.label(class='form-control-label')}}
        {{form.title(class='form-control form-control-lg')}}
      </div>
      <div class="form-group">
        {{form.text.label(class='form-control-label')}}
        {{form.text(class='form-control form-control-lg')}}
      </div>
      <div class="form-group">
        {{form.submit(class='btn btn-outline-info')}}
      </div>
    </form>
   </div>

{% endblock %}

myproject/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron jumbotron-fluid" style="text-align:center;background-image:url('https://images.unsplash.com/photo-1510519138101-570d1dca3d66?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1331&q=80');background-size:cover; background-position: center center; height:500px" >
  <h1 style="color: #BFBD9F; ">Welcome to the Blogging Site</h1><br>
</div>


<!Display the blogs!>
<div class="container">

  {% for post in blog_posts.items %}

    <div class="card">
      <h5 class="card-header">Recent</h5>
      <div class="card-body">
        <h2><a class="card-title" href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{url_for('users.user_posts',username =post.author.username )}}">Written by: {{post.author.username}}</a>
        <p>Published on: {{post.date.strftime('%Y-%m-%d')}}</p>
        <a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}" class="btn btn-primary">Read Blog</a>
      </div>
    </div>

  {% endfor %}


<!Pagination Bar at the bottom!>
</div>
<nav aria-label= 'Page Navigation example'>
  <ul class="pagination justify-content-center">

    {% for page_num in blog_posts.iter_pages(left_edge = 1, right_edge=1, left_current=1, right_current=2)%}

      {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
          <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a>
        </li>
      {% else %}
      <li class="page-item ">
        <a class="page-link" href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a>
      </li>
      {% endif %}
    {% endfor %}

  </ul>

</nav>

<!Footer!>
<footer class="footer" style="text-align:center; background-color:#141B1A; height:50px;">
  <p style="color: white; padding-top:10px; ">Produced by Pradnyal Gandhi</p>
</footer>

{% endblock %}

myproject/templates/info.html
<!CREATING AN INFO TEMPLATE!> 

{% extends 'base.html '%}

{% block content %}

<div class="jumbotron">
  <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</h2>

</div>

{% endblock %}

myproject/templates/login.html
<!CREATING A LOGIN PAGE TEMPLATE!> 

{% extends 'base.html'%}

{% block content %}

<form  method="POST">
  {{form.hidden_tag()}}
  <div class="container">
    {{form.email.label(class='form-control-label')}}
    {{form.email(class='form-control form-control-dark')}}<br>
  </div>
  <div class="container">
    {{form.password.label(class='form-control-label')}}
    {{form.password(class='form-control form-control-dark')}}<br>
  </div>
  <div class="container">
    {{form.submit()}}
  </div>

</form>

{% endblock %}

myproject/templates/register.html
<!CREATING A REGISTATION PAGE TEMPLATE!> 

{% extends 'base.html'%}

{% block content %}

<form  method="POST">

  {{form.hidden_tag()}}
  <div class="container">
    {{form.email.label(class='form-control-label')}}
    {{form.email(class='form-control form-control-lg')}}<br>
  </div>
  <div class="container">
    {{form.username.label(class='form-control-label')}}
    {{form.username(class='form-control form-control-lg')}}<br>
  </div>
  <div class="container">
    {{form.password.label(class='form-control-label')}}
    {{form.password(class='form-control form-control-lg')}}<br>
  </div>
  <div class="container">
    {{form.pass_confirm.label(class='form-control-label')}}
    {{form.pass_confirm(class='form-control form-control-lg')}}<br>
  </div>
  <div class="container">
    {{form.submit()}}
  </div>

</form>

{% endblock %}

myproject/templates/user_blog_posts.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="jumbotron">
    <div align= "center">
      <h1>Blogs of user: {{user.username}}</h1>

  </div>
</div>

{% for post in blog_posts.items %}

  <h2 style="text-align:center"><a href="{{url_for('blog_posts.blog_post',blog_post_id = post.id)}}">{{post.title}}</a></h2><br>
  Written by : <a href="url_for('users.user_posts',username = post.author.username)">{{post.author.username}}</a>
  <p class="text-muted"> Published on: {{post.date.strftime('%Y-%m-%d')}}</p>
  <br>
  <p>{{post.text}}</p>
  <br>

{% endfor %}
</div>

<nav aria-label= 'Page Navigation example'>
  <ul class="pagination justify-content-center">
    {% for page_num in blog_posts.iter_pages(left_edge = 1, right_edge=1, left_current=1, right_current=2)%}
      {% if blog_posts.page == page_num %}
        <li class="page-item disabled">
          <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}}</a>
        </li>

      {% else %}
      <li class="page-item ">
        <a class="page-link" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}}</a>
      </li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>
{% endblock %}